export const AlchemyNFTResponse = {
  contract: {
    address: '0xAA7f515b01C04E632c7837f1a80f67eA3f3Fc58B',
    name: 'Engie',
    symbol: 'TOKEN',
    totalSupply: '7',
    tokenType: 'ERC721',
    contractDeployer: null,
    deployedBlockNumber: null,
    openSeaMetadata: {
      floorPrice: null,
      collectionName: null,
      collectionSlug: null,
      safelistRequestStatus: null,
      imageUrl: null,
      description: null,
      externalUrl: null,
      twitterUsername: null,
      discordUrl: null,
      bannerImageUrl: null,
      lastIngestedAt: null,
    },
    isSpam: null,
    spamClassifications: [],
  },
  tokenId: '65',
  tokenType: 'ERC721',
  name: 'Crossmint Example NFT',
  description: 'My NFT created via the mint API!',
  tokenUri:
    'https://ipfs.io/ipfs/QmaDqJbwXNo3PKuKSu7bh1XeRA8ypQeMRKAqCc7gVPbHWD',
  image: {
    cachedUrl:
      'https://ipfs.io/ipfs/QmaToZn4VEjF7q4CAudPaNka6AD484xuuEZSXmTLJPDLVE',
    thumbnailUrl: null,
    pngUrl: null,
    contentType: null,
    size: null,
    originalUrl:
      'https://ipfs.io/ipfs/QmaToZn4VEjF7q4CAudPaNka6AD484xuuEZSXmTLJPDLVE',
  },
  raw: {
    tokenUri: 'ipfs://QmaDqJbwXNo3PKuKSu7bh1XeRA8ypQeMRKAqCc7gVPbHWD',
    metadata: {
      name: 'Crossmint Example NFT',
      image: 'ipfs://QmaToZn4VEjF7q4CAudPaNka6AD484xuuEZSXmTLJPDLVE',
      description: 'My NFT created via the mint API!',
    },
    error: null,
  },
  collection: null,
  mint: {
    mintAddress: null,
    blockNumber: null,
    timestamp: null,
    transactionHash: null,
  },
  owners: ['0xb8a976ad1d87d070b5e5806b98a768b4bb4e4847'],
  timeLastUpdated: '2024-04-11T11:29:43.950Z',
};
