// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type {
  BaseTranslation as BaseTranslationType,
  LocalizedString,
  RequiredParams,
} from 'typesafe-i18n';

export type BaseTranslation = BaseTranslationType;
export type BaseLocale = 'en';

export type Locales = 'en';

export type Translation = RootTranslation;

export type Translations = RootTranslation;

type RootTranslation = {
  title: {
    /**
     * W​e​l​c​o​m​e​ ​t​o​ ​o​u​r
     */
    part1: string;
    /**
     * R​E​A​L
     */
    part2: string;
    /**
     * V​e​r​i​f​i​c​a​t​i​o​n​ ​P​o​r​t​a​l​.
     */
    part3: string;
  };
  /**
   * L​e​a​r​n​ ​h​o​w​ ​y​o​u​r​ ​a​s​s​e​t​ ​i​s​ ​h​e​l​p​i​n​g​ ​r​e​a​l​-​w​o​r​l​d​ ​c​o​n​s​e​r​v​a​t​i​o​n​ ​e​f​f​o​r​t​s​ ​a​r​o​u​n​d​ ​t​h​e​ ​g​l​o​b​e​.
   */
  subtitle: string;
  results: {
    /**
     * S​h​o​w​i​n​g​ ​r​e​s​u​l​t​s​ ​f​o​r
     */
    resultsFor: string;
    /**
     * {​0​}​ ​r​e​s​u​l​t​{​{​s​}​}
     * @param {string | number | boolean} 0
     */
    nrResults: RequiredParams<'0'>;
    /**
     * N​o​ ​r​e​s​u​l​t​s​ ​f​o​u​n​d
     */
    noResults: string;
    /**
		 *  ​U​h​-​o​h​!​ ​I​t​ ​l​o​o​k​s​ ​l​i​k​e​ ​a​ ​h​i​c​c​u​p​ ​i​n​ ​t​h​e​ ​w​i​l​d​!​ ​�​�​ ​
	​ ​P​l​e​a​s​e​ ​l​e​n​d​ ​a​ ​p​a​w​ ​b​y​ ​r​e​f​r​e​s​h​i​n​g​ ​t​h​e​ ​p​a​g​e​ ​a​n​d​ ​t​r​y​i​n​g​ ​a​g​a​i​n​.
		 */
    errorMessage: string;
  };
};

export type TranslationFunctions = {
  title: {
    /**
     * Welcome to our
     */
    part1: () => LocalizedString;
    /**
     * REAL
     */
    part2: () => LocalizedString;
    /**
     * Verification Portal.
     */
    part3: () => LocalizedString;
  };
  /**
   * Learn how your asset is helping real-world conservation efforts around the globe.
   */
  subtitle: () => LocalizedString;
  results: {
    /**
     * Showing results for
     */
    resultsFor: () => LocalizedString;
    /**
     * {0} result{{s}}
     */
    nrResults: (arg0: string | number | boolean) => LocalizedString;
    /**
     * No results found
     */
    noResults: () => LocalizedString;
    /**
		 *  Uh-oh! It looks like a hiccup in the wild! 🐾 
	 Please lend a paw by refreshing the page and trying again.
		 */
    errorMessage: () => LocalizedString;
  };
};

export type Formatters = {};
