sources:
  - name: subgraph-identifiers
    handler:
      graphql:
        endpoint: '{{&GRAPHQL_ENDPOINT}}'
  - name: subgraph-derivatives
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/sovereign-nature/derivatives
  - name: ipfs-pinata
    handler:
      jsonSchema:
        endpoint: 'https://sni.mypinata.cloud/'
        operations:
          - type: Query
            field: ipfsMetadata
            path: /ipfs/{args.cid}
            method: GET
            responseSchema: ./json-schemas/metadata.json
        operationHeaders:
          x-pinata-gateway-token: '{{&PINATA_TOKEN}}'
    transforms:
      - resolversComposition:
          mode: bare
          compositions:
            - resolver: 'Query.ipfsMetadata'
              composer: './middleware/getCid.ts'
additionalTypeDefs: |
  extend type SNI {
    metadata: Identifier_Token_Metadata!,
    derivatives: [Derivative]!
  }
additionalResolvers:
  - targetTypeName: SNI
    targetFieldName: metadata
    sourceName: ipfs-pinata
    sourceTypeName: Query
    sourceFieldName: ipfsMetadata
    requiredSelectionSet: |
      {
        tokenURI
      }
    sourceArgs:
      cid: '{root.tokenURI}'
  - targetTypeName: SNI
    targetFieldName: derivatives
    sourceName: subgraph-derivatives
    sourceTypeName: Query
    sourceFieldName: derivatives
    sourceArgs:
      where: '{identifierAddress_in:["1287:0xfd3434f66093f8007B30Bc44D3c467E660589059:0"]}'
# plugins:
# - httpCache
# - responseCache:
#     includeExtensionMetadata: true
# cache:
#   cfwKv:
#     namespace: MESH
