sources:
  - name: TheGraph
    handler:
      graphql:
        endpoint: '{{&GRAPHQL_ENDPOINT}}'
  - name: Pinata
    handler:
      jsonSchema:
        endpoint: 'https://ipfs.io'
        operations:
          - type: Query
            field: ipfsMetadata
            path: /ipfs/{args.cid}
            method: GET
            responseSchema: ./json-schemas/metadata.json
    transforms:
      - resolversComposition:
          mode: bare
          compositions:
            - resolver: 'Query.ipfsMetadata'
              composer: './middleware/getCid.ts'
additionalTypeDefs: |
  extend type SNI {
    metadata: Identifier_Token_Metadata
  }
additionalResolvers:
  - targetTypeName: SNI
    targetFieldName: metadata
    sourceName: Pinata
    sourceTypeName: Query
    sourceFieldName: ipfsMetadata
    requiredSelectionSet: |
      {
        tokenURI
      }
    sourceArgs:
      cid: '{root.tokenURI}'
