sources:
  - name: TheGraph
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/sovereign-nature/sni
  - name: Pinata
    handler:
      jsonSchema:
        endpoint: https://gateway.pinata.cloud/
        operations:
          - type: Query
            field: ipfsMetadata
            path: /ipfs/{args.cid}
            method: GET
            responseSchema: ./json-schemas/metadata.json
additionalTypeDefs: |
  extend type SNI {
    metadata: Identifier_Token_Metadata @resolveTo(
      sourceName: "Pinata",
      sourceTypeName: "Query",
      sourceFieldName: "ipfsMetadata",
      requiredSelectionSet: "{ tokenURI }",
      sourceArgs: {
        "input.cid": "{root.tokenURI}"
      }
    )
  }
transforms:
  - resolversComposition:
      mode: bare
      compositions:
        - resolver: 'Query.ipfsMetadata'
          composer: './middleware/getCid.ts'
