# type SNI {
#   id: ID!
#   status: Int!
#   createdTimestamp: Int!
#   updatedTimestamp: Int
#   owner: ID!
#   oracle: ID!
#   collectionName: String!
#   symbol: String!
#   name: String!
#   description: String
#   image: String
#   properties: SNIProperties
# }

type SNI {
  id: ID!
  status: Int!

  createdAt: Int!
  updatedAt: Int!
  owner: ID!
  oracle: ID!
  collectionName: String!
  symbol: String!
  name: String!
  description: String
  image: String
  statusDescription: String!
  taxonId: String!
  tokenId: String!
  tokenURI: String!
  geometry: String!
  conservationStatus: Int!



}

type SNIProperties {
  # Contains JSON describing status values like {"0": "Good", "1": "Bad"}
  statusDescription: String
  taxonId: String
  conservationStatus: String
  # Geometry in WKT standard
  geometry: String
}

type Query {
  snis: [SNI!]!
  sni(id: ID!): SNI
}
