name = "api"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = [ "nodejs_compat" ]

[vars]
CROSSMINT_API_URL = "https://staging.crossmint.com/api/2022-06-09/collections"

[env.production.vars]
CROSSMINT_API_URL = "https://crossmint.com/api/2022-06-09/collections"
