name = "api"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
logpush = false
workers_dev = false

vars = { ENVIRONMENT = "dev", CROSSMINT_API_URL = "https://staging.crossmint.com/api/2022-06-09/collections", DOTPHIN_NETWORK = "opal", DOTPHIN_PROOFS_COLLECTION_ID = 3030, DOTPHIN_COLLECTION_ID = 3758 }

queues.producers = [
  { queue = "minting-queue", binding = "MINTING_QUEUE" },
  { queue = "evolution-queue", binding = "EVOLUTION_QUEUE" },
]
queues.consumers = [
  { queue = "minting-queue", dead_letter_queue = "minting-queue-dlq", max_concurrency = 15, max_batch_size = 1 },
  { queue = "evolution-queue", dead_letter_queue = "evolution-queue-dlq", max_concurrency = 15, max_batch_size = 1 },
]

kv_namespaces = [
  { binding = "EMAILS_KV", id = "a008ae3da87c4f0ebf3efc2812b2cde4" },
]

d1_databases = [
  { binding = "SESSIONS_DB", database_name = "sessions-db", database_id = "4fff6376-d5de-4b1c-a8ec-b9ea13ed4eec" },
]

# Production Configuration Overrides
[env.production]
name = "api"
tail_consumers = [{ service = "api-tail" }]

vars = { ENVIRONMENT = 'production', CROSSMINT_API_URL = "https://crossmint.com/api/2022-06-09/collections", DOTPHIN_NETWORK = "unique", DOTPHIN_PROOFS_COLLECTION_ID = 665, DOTPHIN_COLLECTION_ID = 813 }

queues.producers = [
  { queue = "minting-queue", binding = "MINTING_QUEUE" },
  { queue = "evolution-queue", binding = "EVOLUTION_QUEUE" },
]
queues.consumers = [
  { queue = "minting-queue", dead_letter_queue = "minting-queue-dlq", max_concurrency = 15, max_batch_size = 1 },
  { queue = "evolution-queue", dead_letter_queue = "evolution-queue-dlq", max_concurrency = 15, max_batch_size = 1 },
]

kv_namespaces = [
  { binding = "EMAILS_KV", id = "a008ae3da87c4f0ebf3efc2812b2cde4" },
]

d1_databases = [
  { binding = "SESSIONS_DB", database_name = "sessions-db", database_id = "4fff6376-d5de-4b1c-a8ec-b9ea13ed4eec" },
]

# Stage Configuration Overrides
[env.staging]
name = "stg-api"
# tail_consumers = [{ service = "stg-api-tail" }]
workers_dev = true

vars = { ENVIRONMENT = "staging", CROSSMINT_API_URL = "https://staging.crossmint.com/api/2022-06-09/collections", DOTPHIN_NETWORK = "opal", DOTPHIN_PROOFS_COLLECTION_ID = 3551, DOTPHIN_COLLECTION_ID = 3773 }

queues.producers = [
  { queue = "minting-queue", binding = "MINTING_QUEUE" },
  { queue = "evolution-queue", binding = "EVOLUTION_QUEUE" },
]
queues.consumers = [
  { queue = "minting-queue", dead_letter_queue = "minting-queue-dlq", max_concurrency = 15, max_batch_size = 1 },
  { queue = "evolution-queue", dead_letter_queue = "evolution-queue-dlq", max_concurrency = 15, max_batch_size = 1 },
]

# TODO: Setup staging KVs
kv_namespaces = [
  { binding = "EMAILS_KV", id = "a008ae3da87c4f0ebf3efc2812b2cde4" },
]

# TODO: Setup staging DBs
d1_databases = [
  { binding = "SESSIONS_DB", database_name = "stg-sessions-db", database_id = "4fff6376-d5de-4b1c-a8ec-b9ea13ed4eec" },
]
