name = "api"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
logpush = false
tail_consumers = [{service = "api-tail"}]

[vars]
CROSSMINT_API_URL = "https://crossmint.com/api/2022-06-09/collections"

[env.staging.vars]
CROSSMINT_API_URL = "https://staging.crossmint.com/api/2022-06-09/collections"

[[queues.producers]]
queue = "minting-queue"
binding = "MINTING_QUEUE"

[[queues.consumers]]
queue = "minting-queue"
dead_letter_queue = "minting-queue-dlq"
max_concurrency = 15
max_batch_size = 1

[[kv_namespaces]]
binding = "MINTING_KV"
id = "0f4988a01242450187f4ee6ca522a5d6"
preview_id = "0f4988a01242450187f4ee6ca522a5d6"

[[kv_namespaces]]
binding = "CLAIMS_KV"
id = "974b532adcea43e8b9b90bffe8c834cf"
preview_id = "974b532adcea43e8b9b90bffe8c834cf"
