name: Code Quality

on:
  push:
  pull_request:

jobs:
  code-quality:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      DIRECTUS_API_KEY: ${{ secrets.DIRECTUS_API_KEY }}
      PUBLIC_WALLET_CONNECT_PROJECT_ID: ${{ secrets.PUBLIC_WALLET_CONNECT_PROJECT_ID }}
      OPEN_SEA_API_KEY: ${{ secrets.OPEN_SEA_API_KEY }}
      NFTSCAN_API_KEY: ${{ secrets.NFTSCAN_API_KEY }}
      VERCEL_URL: 'empty'
      TURBO_REMOTE_ONLY: true
      FLAG_SHOW_DRAFT_NEWS: ${{ secrets.FLAG_SHOW_DRAFT_NEWS }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm i
      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps
      - name: Lint
        run: pnpm lint
      - name: Test
        run: pnpm test
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
