name: Code Quality

on:
  push:
  pull_request:

jobs:
  code-quality:
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      DIRECTUS_API_KEY: ${{ secrets.DIRECTUS_API_KEY }}
      PUBLIC_WALLET_CONNECT_PROJECT_ID: ${{ secrets.PUBLIC_WALLET_CONNECT_PROJECT_ID }}
      OPEN_SEA_API_KEY: ${{ secrets.OPEN_SEA_API_KEY }}
      NFTSCAN_API_KEY: ${{ secrets.NFTSCAN_API_KEY }}
      VERCEL_URL: 'empty'
      TURBO_REMOTE_ONLY: true
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      # - uses: pnpm/action-setup@v2
      #   with:
      #     run_install: false
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - run: pnpm i
      - run: pnpm lint
      - run: pnpm test
