name: Deploy Cloudflare Workers
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Workers
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          run_install: false
      - name: Deploy Assets Gateway
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: './apps/assets-gateway'
          packageManager: 'pnpm'
      - name: Deploy Web3 Highlights
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: './apps/web3-highlights'
          packageManager: 'pnpm'
      - name: Deploy Web3 Highlights
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: './apps/api'
          packageManager: 'pnpm'
