query sniListAll {
  snis {
    id
    owner
    status
    createdAt
    updatedAt
    name
    collectionName
  }
}

query sniFilterCreatedAt($createdAt: BigInt) {
  snis(where: { createdAt_gte: $createdAt }) {
    id
    owner
    status
    createdAt
    updatedAt
    name
    collectionName
  }
}

query sniFilterUpdatedAt($updatedAt: BigInt) {
  snis(where: { updatedAt_gte: $updatedAt }) {
    id
    owner
    status
    createdAt
    updatedAt
    name
    collectionName
  }
}

query sniFilterStatus($status: BigInt) {
  snis(where: { status: $status }) {
    id
    owner
    status
    createdAt
    updatedAt
    name
    collectionName
  }
}

query sniFilterId($id: ID) {
  snis(where: { id: $id }) {
    id
    owner
    status
    createdAt
    updatedAt
    name
    collectionName
  }
}

query sniFilterOwner($owner: Bytes) {
  snis(where: { owner_contains: $owner }) {
    id
    owner
    status
    createdAt
    updatedAt
    name
    collectionName
  }
}

query sniFilterName($name: String) {
  snis(where: { name_contains: $name }) {
    id
    owner
    status
    createdAt
    updatedAt
    name
    collectionName
  }
}

query sniDetail($sniId: ID!) {
  sni(id: $sniId) {
    id
    status
    name
    createdAt
    updatedAt
    owner
    oracle
    collectionName
    symbol
    name
    description
    image
    statusDescription
    taxonId
    tokenId
    tokenURI
    geometry
    conservationStatus
  }
}
