query sniList {
  snis {
    id
    owner
    status
    createdAt
    updatedAt
    name
    collectionName
  }
}

query sniDetail($sniId: ID!) {
  sni(id: $sniId) {
    id
    status
    name
    createdAt
    updatedAt
    owner
    oracle
    collectionName
    symbol
    name
    description
    image
    statusDescription
    taxonId
    tokenId
    tokenURI
    geometry
    conservationStatus
  }
}
